on: [pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Lint flutter code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.16
  use-script:
    runs-on: ubuntu-latest
    name: Script
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - uses: actions/setup-node@v4
      - run: |
          curl https://raw.githubusercontent.com/ValentinVignal/action-dart-analyze/refs/heads/script/test.sh -o script.sh
          sh script.sh